spring:
  # 解决 2.6以上的spring boot 和 swagger 不兼容的问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 100
      max-lifetime: 180000
      #使用utf8mb4编码
      connectionInitSql: SET NAMES utf8mb4 COLLATE utf8mb4_general_ci
  redis:
    database: 14
    host: 192.168.0.38
    port: 6379
    password: 123456
    timeout: 2000  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8      # 连接池中的最大空闲连接
        min-idle: 1       # 连接池中的最小空闲连接

# mybatis-plus
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: cn.springlet.mybatisplus.handler
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 枚举：com.baomidou.mybatisplus.annotation.IdType
      id-type: ASSIGN_ID
      logic-delete-value: id
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#日志
logging:
  config: classpath:logback-spring.xml
  params:
    path: logs
    #    path: /home/springlet/logs/${spring.application.name}
    name: app
    level: INFO
    file:
      max-size: 100MB
      max-history: 10


springlet:
  crypt:
    rsa:
      enabled: true
      private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCgMEl9wljclROopLnF8WPh2CTrZwtCqckeHOdjpdxmSa5pNXfxqQwwp62bLmX6ug7VzByEIHlVtu5G99Dqu19GajYj4yJD4eseHpmjHuVUvecnAhqOgrawCZplobPYO/gQ7s20HFE9X/J+MhHK0S8gUUD79ZR/8L6rKiKyCUa0rny/pzu0NIHaVIgTKfnk/m3s0E0IWHC4fT3XPUOIeS0oAC2LJpVbEb/hdPQu1lOPmsvkjET0WBLKS4X7eF4g+UeTsQQdiHhEjR4AdJhE3pMgJmAOyIvlpk7A3zvVYPELN4WHu2VSyhvuE58aL6K49KcRtYWq7pD3BmafLnDDDm1xAgMBAAECggEAfbwJI2YV++YjzR6nFuDXZqESsZdrNkMwsqs7UHMS4VL6TGiEojHveI1U7lZoA3phRJ120Jrwwj/ZHelMmcLDEPEzV83jymac90JLk8cfePmqY2r6T1v4a4rOHvHiyVqg5yGaYsJLXiJeo4FHh+vT0skUefCURCxCbPWg0CAJ2K1S3nauVlhGFCrgUXhvIK+P5c8SHnVnlBNRNr9muSyTh/dEVdswjKo4/cqA50gMsE1ulCYO3rdFX3TV+8U5F19stiWHvgOL2uh8K6sc4gU4kaQssMIogO1C58qdmXcBEvX+7bWDymmNutTDkn3rWdSsLrP6wR16dEWLnWpfrWI08QKBgQDTFfKkBj7GpLCxvWvzKC7+d9xiksqCq2PSwvAy3SNpen7qzSqIC+vGK+c53yXunHrJFd+rZVyZmn4lYOM/dcvfdN2QVzJTRlpoDnRbfsBizAHE3BGXbmhvKEQ0cKKq8rt6Ief554xy/6pVNPzDOMGcNZZ01MThdSgMK70CsMgrPQKBgQDCRewgiQQG4ZIodObgRJzUpg/R4yBEEaIrC55reVa/CCtPDHALQnG8TFYe/QxbSxw7/YFu1K21f8twdMjNXk04tzeryxj/e3TwR6vXhlpAy/7AtPZcNQEwnU+SdWMLp+i6frs9rLIviSkQXqtkPLtZypukYGp5B6x6iP3g30o+RQKBgQDFo30mWrqYX0cZhFP4vZ0SocN1gB+grTyv79napfcsIYeH7UVvUEoXqK+9HdR0T4sfkB12a1eCcoa+FLNxjaevt8pkBWCXW/32A+KqcElNt9nIKo1GDhg2S6tgtj14dgFXXzvGXyi/2+XuFci8OP3+dqZDCZy1xG4UxzcXt9ITuQKBgDJiehQSFQZH2GU/tGUzxkzsaKvxsPuWay2ozMRo6tOOpdTRj/mLmP3R+n/89whyWXdBjyEUbZzl8PhQgYepznNIKVsXyHryJOjwXaP/B0dI4OBPzpkpcg6OrgV5BmAOgzBjD+K1+FyVwR2qv962VYy7HFSsYNDU6am5/8YjgxjVAoGBAKHYgCLqvPPgIEsG6buMWcivUKrb4t5Bn5Fd6J0ydCJEV07xcBAwlvdL65tQB4R3u4xEYz1wtvn/DlRf/6WtV7HlblShIOGIRd4UiPyS61h6mvK8DUWXPpWRtfSwXPn6F80WYRkMQ6+Y6+6Xf6sThWyctE3KnksEcN/PCfaBzTEm
      public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoDBJfcJY3JUTqKS5xfFj4dgk62cLQqnJHhznY6XcZkmuaTV38akMMKetmy5l+roO1cwchCB5VbbuRvfQ6rtfRmo2I+MiQ+HrHh6Zox7lVL3nJwIajoK2sAmaZaGz2Dv4EO7NtBxRPV/yfjIRytEvIFFA+/WUf/C+qyoisglGtK58v6c7tDSB2lSIEyn55P5t7NBNCFhwuH091z1DiHktKAAtiyaVWxG/4XT0LtZTj5rL5IxE9FgSykuF+3heIPlHk7EEHYh4RI0eAHSYRN6TICZgDsiL5aZOwN871WDxCzeFh7tlUsob7hOfGi+iuPSnEbWFqu6Q9wZmny5www5tcQIDAQAB
  dingtalk:
    error:
      secret:
      webhook:
  swagger2:
    enabled: true
  redis:
    cache:
      timeout: 21600
  xxljob:
    access-token:
    admin:
      admin-addresses: http://192.168.0.38:7777/xxl-job-admin
    executor:
      appname: ${spring.application.name}
      logpath: ${logging.params.path}/jobhandler
      logretentiondays: 30
  # 阿里云 rocketmq
  rocketmq:
    accessKey: LTAI5t9jPbbhtXN2KXpAGT9C
    secretKey: M3Vf7kLr0mF02PvTYsD43Ho5UEWHOE
    nameSrvAddr: http://MQ_INST_1436122467007897_BXx88R7n.mq-internet-access.mq-internet.aliyuncs.com:80
    topic: cutepet-topic
    groupId: GID-${spring.profiles.active}-${spring.application.name}-group
    #区分 环境+服务
    tag: ${spring.profiles.active}-${spring.application.name}
    instanceId: MQ_INST_1436122467007897_BXx88R7n